name: CI

on: [push, pull_request]

jobs:
  build-and-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: sudo apt-get install -y cmake ninja-build gcc-arm-none-eabi
      - name: Cache pico-sdk
        uses: actions/cache@v4
        with:
          path: |
            build/_deps/pico_sdk-src
            build/_deps/pico_sdk-build
          key: ${{ runner.os }}-pico-sdk-${{ hashFiles('CMakeLists.txt', 'pico_sdk_import.cmake') }}
      - name: Configure
        run: cmake -S . -B build -G Ninja -DPICO_SDK_FETCH_FROM_GIT=1
      - name: Build
        run: cmake --build build