name: CI

on: [push, pull_request]

jobs:
  build-and-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: sudo apt-get install -y cmake ninja-build clang-tidy python3-pip gcc-arm-none-eabi
      - name: Configure
        run: cmake -S . -B build -G Ninja -DPICO_SDK_FETCH_FROM_GIT=1
      - name: Build
        run: cmake --build build
      - name: Run clang-tidy
        run: clang-tidy multicore.c -p build --quiet || exit 1